create table user_story
(
    id                  bigint generated by default as identity,
    story_title         varchar(100),
    users_story         varchar(400),
    acceptance_criteria varchar(400),
    estimation          double not null,
    status              varchar(20),
    primary key (id)
);